### ISSUE TITLE
Get Error when Recovering the Koala Model Weights

### ISSUE THREAD

**Issue by zhangsanfeng86** [young-geng/EasyLM#18]
Hi @young-geng 
Thank you for release!

Get Error when Recovering the Koala Model Weights

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/73547638/230428617-9c3907f3-aea9-4f1b-bb9e-3c554fb63ff9.png">

**Comment by zhangsanfeng86** [comment]
koala_13b_diff_v2  download from huggleface

**Comment by young-geng** [comment]
Are you diffing against a base LLaMA model if different size?

**Comment by zhangsanfeng86** [comment]
The ‘load_base_checkpoint’ is from the output of  'EasyLM.models.llama.convert_torch_to_easylm.py' .

**Comment by young-geng** [comment]
On the surface it seems that JAX is complaining that the nested dictionary structure is different for the based weights and the diff. The most likely cause is the the based model you converted from is of different size from the diff. Did you happen to convert the 7b base model instead of the 13b model?
