### ISSUE TITLE
Converting the Koala Weights to HF Transformers

### ISSUE THREAD

**Issue by xiujiesong** [young-geng/EasyLM#89]
Hi, 

Thanks for the great work. To convert the Koala model weights to HuggingFace Transformers format, the following script is given:

```
python -m EasyLM.models.llama.convert_easylm_to_hf \
    --load_checkpoint='params::path/to/koala/checkpoint' \
    --tokenizer_path='path/to/llama/tokenizer' \
    --model_size='13b' \  # '7b', '13b', '30b' or '65b'
    --output_dir='path/to/output/huggingface/koala/checkpoint'
```

so the load_checkpoint is the path to weights diff (e.g. koala_13b_diff_v2) and tokenizer_path is the path to the Meta's released weights of LLama, right?

**Comment by young-geng** [comment]
Due to the llama license, we are not able to directly release Koala weights. Therefore, we released it as a diff against the base LLaMA model weights. Therefore, you need to obtain the base LLaMA weights from Meta and recover the Koala weights first. Please follow the [Koala documentation here](https://github.com/young-geng/EasyLM/blob/main/docs/koala.md).
